#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
abbr cp="cp -iv"
abbr mv="mv -iv"
abbr rm="rm -v"
abbr rma="rm -rfv *(D)"
abbr mkd="mkdir -pv"
abbr yt="youtube-dl --add-metadata -i"
abbr yta="yt -x -f bestaudio/best"
abbr ffmpeg="ffmpeg -hide_banner"
abbr tmux="tmux -f $HOME/.config/tmux/tmux.conf"
abbr sdn="shutdown -h now"
abbr cat="bat"
abbr pbcopy="xclip -selection clipboard"
abbr pbpaste="xclip -selection clipboard -o"

# Colorize commands when possible.
abbr ls="exa --icons --long"
abbr l="exa --icons --long -alh"
abbr grep="grep --color=auto"
abbr diff="diff --color=auto"
abbr ccat="highlight --out-format=ansi"

# These common commands are just too long! Abbreviate them.
abbr ka="killall"
abbr g="git"
abbr sdn="shutdown -h now"
abbr e="$EDITOR"
abbr v="$EDITOR"
abbr p="pacman"
abbr xi="sudo xbps-install"
abbr xr="sudo xbps-remove -R"
abbr xq="xbps-query"
abbr z="zathura"

abbr ref="shortcuts >/dev/null; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/shortcutrc ; source ${XDG_CONFIG_HOME:-$HOME/.config}/shell/zshnameddirrc"
